package model.vo;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 08 15:07:12 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StEnWeekVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public StEnWeekVOImpl() {
    }

    /**
     * Returns the bind variable value for systemdate.
     * @return bind variable value for systemdate
     */
    public Date getsystemdate() {
        return (Date) getNamedWhereClauseParam("systemdate");
    }

    /**
     * Sets <code>value</code> for bind variable systemdate.
     * @param value value to bind as systemdate
     */
    public void setsystemdate(Date value) {
        setNamedWhereClauseParam("systemdate", value);
    }
}

