package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 08 15:07:11 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StEnWeekVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        WeekStartDate,
        WeekEndDate;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int WEEKSTARTDATE = AttributesEnum.WeekStartDate.index();
    public static final int WEEKENDDATE = AttributesEnum.WeekEndDate.index();

    /**
     * This is the default constructor (do not remove).
     */
    public StEnWeekVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute WeekStartDate.
     * @return the WeekStartDate
     */
    public Timestamp getWeekStartDate() {
        return (Timestamp) getAttributeInternal(WEEKSTARTDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute WeekEndDate.
     * @return the WeekEndDate
     */
    public Timestamp getWeekEndDate() {
        return (Timestamp) getAttributeInternal(WEEKENDDATE);
    }
}

