package model.vo;

import java.math.BigDecimal;

import model.eo.TimesheetUsersMappingEOImpl;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 17 12:02:19 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TimesheetUsersMappingVORowImpl extends ViewRowImpl {
    public static final int ENTITY_TIMESHEETUSERSMAPPINGEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        TimeSheetId,
        SubmittedBy,
        SubmittedTo,
        MappingId;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int TIMESHEETID = AttributesEnum.TimeSheetId.index();
    public static final int SUBMITTEDBY = AttributesEnum.SubmittedBy.index();
    public static final int SUBMITTEDTO = AttributesEnum.SubmittedTo.index();
    public static final int MAPPINGID = AttributesEnum.MappingId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TimesheetUsersMappingVORowImpl() {
    }

    /**
     * Gets TimesheetUsersMappingEO entity object.
     * @return the TimesheetUsersMappingEO
     */
    public TimesheetUsersMappingEOImpl getTimesheetUsersMappingEO() {
        return (TimesheetUsersMappingEOImpl) getEntity(ENTITY_TIMESHEETUSERSMAPPINGEO);
    }

    /**
     * Gets the attribute value for TIME_SHEET_ID using the alias name TimeSheetId.
     * @return the TIME_SHEET_ID
     */
    public BigDecimal getTimeSheetId() {
        return (BigDecimal) getAttributeInternal(TIMESHEETID);
    }

    /**
     * Sets <code>value</code> as attribute value for TIME_SHEET_ID using the alias name TimeSheetId.
     * @param value value to set the TIME_SHEET_ID
     */
    public void setTimeSheetId(BigDecimal value) {
        setAttributeInternal(TIMESHEETID, value);
    }

    /**
     * Gets the attribute value for SUBMITTED_BY using the alias name SubmittedBy.
     * @return the SUBMITTED_BY
     */
    public BigDecimal getSubmittedBy() {
        return (BigDecimal) getAttributeInternal(SUBMITTEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBMITTED_BY using the alias name SubmittedBy.
     * @param value value to set the SUBMITTED_BY
     */
    public void setSubmittedBy(BigDecimal value) {
        setAttributeInternal(SUBMITTEDBY, value);
    }

    /**
     * Gets the attribute value for SUBMITTED_TO using the alias name SubmittedTo.
     * @return the SUBMITTED_TO
     */
    public BigDecimal getSubmittedTo() {
        return (BigDecimal) getAttributeInternal(SUBMITTEDTO);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBMITTED_TO using the alias name SubmittedTo.
     * @param value value to set the SUBMITTED_TO
     */
    public void setSubmittedTo(BigDecimal value) {
        setAttributeInternal(SUBMITTEDTO, value);
    }

    /**
     * Gets the attribute value for MAPPING_ID using the alias name MappingId.
     * @return the MAPPING_ID
     */
    public BigDecimal getMappingId() {
        return (BigDecimal) getAttributeInternal(MAPPINGID);
    }

    /**
     * Sets <code>value</code> as attribute value for MAPPING_ID using the alias name MappingId.
     * @param value value to set the MAPPING_ID
     */
    public void setMappingId(BigDecimal value) {
        setAttributeInternal(MAPPINGID, value);
    }
}

