package model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 14 12:01:12 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TimeSheetWeekVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TimeSheetWeekVOImpl() {
    }
}

