package model.vo;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 14 12:01:12 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TimeSheetWeekVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TimeSheetWeekVOImpl() {
    }

    /**
     * Returns the variable value for p_week_st_date.
     * @return variable value for p_week_st_date
     */
    public Date getp_week_st_date() {
        return (Date) ensureVariableManager().getVariableValue("p_week_st_date");
    }

    /**
     * Sets <code>value</code> for variable p_week_st_date.
     * @param value value to bind as p_week_st_date
     */
    public void setp_week_st_date(Date value) {
        ensureVariableManager().setVariableValue("p_week_st_date", value);
    }

    /**
     * Returns the variable value for p_week_en_date.
     * @return variable value for p_week_en_date
     */
    public Date getp_week_en_date() {
        return (Date) ensureVariableManager().getVariableValue("p_week_en_date");
    }

    /**
     * Sets <code>value</code> for variable p_week_en_date.
     * @param value value to bind as p_week_en_date
     */
    public void setp_week_en_date(Date value) {
        ensureVariableManager().setVariableValue("p_week_en_date", value);
    }

    /**
     * Returns the variable value for p_status.
     * @return variable value for p_status
     */
    public String getp_status() {
        return (String) ensureVariableManager().getVariableValue("p_status");
    }

    /**
     * Sets <code>value</code> for variable p_status.
     * @param value value to bind as p_status
     */
    public void setp_status(String value) {
        ensureVariableManager().setVariableValue("p_status", value);
    }
}

