package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import model.eo.TimeSheetDaysEOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.BFileDomain;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 14 16:25:03 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TimeSheetDaysVORowImpl extends ViewRowImpl {


    public static final int ENTITY_TIMESHEETDAYSEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        WeekId,
        Day1,
        Day2,
        Day3,
        Day4,
        Day5,
        Day6,
        Day7,
        TimeSheetId,
        TaskId,
        Notes,
        IsAttached,
        TimeSheetAttachmentsVO,
        TimeSheetTasksVO1;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int WEEKID = AttributesEnum.WeekId.index();
    public static final int DAY1 = AttributesEnum.Day1.index();
    public static final int DAY2 = AttributesEnum.Day2.index();
    public static final int DAY3 = AttributesEnum.Day3.index();
    public static final int DAY4 = AttributesEnum.Day4.index();
    public static final int DAY5 = AttributesEnum.Day5.index();
    public static final int DAY6 = AttributesEnum.Day6.index();
    public static final int DAY7 = AttributesEnum.Day7.index();
    public static final int TIMESHEETID = AttributesEnum.TimeSheetId.index();
    public static final int TASKID = AttributesEnum.TaskId.index();
    public static final int NOTES = AttributesEnum.Notes.index();
    public static final int ISATTACHED = AttributesEnum.IsAttached.index();
    public static final int TIMESHEETATTACHMENTSVO = AttributesEnum.TimeSheetAttachmentsVO.index();
    public static final int TIMESHEETTASKSVO1 = AttributesEnum.TimeSheetTasksVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TimeSheetDaysVORowImpl() {
    }

    /**
     * Gets TimeSheetDaysEO entity object.
     * @return the TimeSheetDaysEO
     */
    public TimeSheetDaysEOImpl getTimeSheetDaysEO() {
        return (TimeSheetDaysEOImpl) getEntity(ENTITY_TIMESHEETDAYSEO);
    }


    /**
     * Gets the attribute value for WEEK_ID using the alias name WeekId.
     * @return the WEEK_ID
     */
    public BigDecimal getWeekId() {
        return (BigDecimal) getAttributeInternal(WEEKID);
    }

    /**
     * Sets <code>value</code> as attribute value for WEEK_ID using the alias name WeekId.
     * @param value value to set the WEEK_ID
     */
    public void setWeekId(BigDecimal value) {
        setAttributeInternal(WEEKID, value);
    }

    /**
     * Gets the attribute value for DAY1 using the alias name Day1.
     * @return the DAY1
     */
    public Integer getDay1() {
        return (Integer) getAttributeInternal(DAY1);
    }

    /**
     * Sets <code>value</code> as attribute value for DAY1 using the alias name Day1.
     * @param value value to set the DAY1
     */
    public void setDay1(Integer value) {
        setAttributeInternal(DAY1, value);
    }

    /**
     * Gets the attribute value for DAY2 using the alias name Day2.
     * @return the DAY2
     */
    public Integer getDay2() {
        return (Integer) getAttributeInternal(DAY2);
    }

    /**
     * Sets <code>value</code> as attribute value for DAY2 using the alias name Day2.
     * @param value value to set the DAY2
     */
    public void setDay2(Integer value) {
        setAttributeInternal(DAY2, value);
    }

    /**
     * Gets the attribute value for DAY3 using the alias name Day3.
     * @return the DAY3
     */
    public Integer getDay3() {
        return (Integer) getAttributeInternal(DAY3);
    }

    /**
     * Sets <code>value</code> as attribute value for DAY3 using the alias name Day3.
     * @param value value to set the DAY3
     */
    public void setDay3(Integer value) {
        setAttributeInternal(DAY3, value);
    }

    /**
     * Gets the attribute value for DAY4 using the alias name Day4.
     * @return the DAY4
     */
    public Integer getDay4() {
        return (Integer) getAttributeInternal(DAY4);
    }

    /**
     * Sets <code>value</code> as attribute value for DAY4 using the alias name Day4.
     * @param value value to set the DAY4
     */
    public void setDay4(Integer value) {
        setAttributeInternal(DAY4, value);
    }

    /**
     * Gets the attribute value for DAY5 using the alias name Day5.
     * @return the DAY5
     */
    public Integer getDay5() {
        return (Integer) getAttributeInternal(DAY5);
    }

    /**
     * Sets <code>value</code> as attribute value for DAY5 using the alias name Day5.
     * @param value value to set the DAY5
     */
    public void setDay5(Integer value) {
        setAttributeInternal(DAY5, value);
    }

    /**
     * Gets the attribute value for DAY6 using the alias name Day6.
     * @return the DAY6
     */
    public Integer getDay6() {
        return (Integer) getAttributeInternal(DAY6);
    }

    /**
     * Sets <code>value</code> as attribute value for DAY6 using the alias name Day6.
     * @param value value to set the DAY6
     */
    public void setDay6(Integer value) {
        setAttributeInternal(DAY6, value);
    }

    /**
     * Gets the attribute value for DAY7 using the alias name Day7.
     * @return the DAY7
     */
    public Integer getDay7() {
        return (Integer) getAttributeInternal(DAY7);
    }

    /**
     * Sets <code>value</code> as attribute value for DAY7 using the alias name Day7.
     * @param value value to set the DAY7
     */
    public void setDay7(Integer value) {
        setAttributeInternal(DAY7, value);
    }

    /**
     * Gets the attribute value for TIME_SHEET_ID using the alias name TimeSheetId.
     * @return the TIME_SHEET_ID
     */
    public BigDecimal getTimeSheetId() {
        return (BigDecimal) getAttributeInternal(TIMESHEETID);
    }

    /**
     * Sets <code>value</code> as attribute value for TIME_SHEET_ID using the alias name TimeSheetId.
     * @param value value to set the TIME_SHEET_ID
     */
    public void setTimeSheetId(BigDecimal value) {
        setAttributeInternal(TIMESHEETID, value);
    }

    /**
     * Gets the attribute value for TASK_ID using the alias name TaskId.
     * @return the TASK_ID
     */
    public BigDecimal getTaskId() {
        return (BigDecimal) getAttributeInternal(TASKID);
    }

    /**
     * Sets <code>value</code> as attribute value for TASK_ID using the alias name TaskId.
     * @param value value to set the TASK_ID
     */
    public void setTaskId(BigDecimal value) {
        setAttributeInternal(TASKID, value);
    }

    /**
     * Gets the attribute value for NOTES using the alias name Notes.
     * @return the NOTES
     */
    public String getNotes() {
        return (String) getAttributeInternal(NOTES);
    }

    /**
     * Sets <code>value</code> as attribute value for NOTES using the alias name Notes.
     * @param value value to set the NOTES
     */
    public void setNotes(String value) {
        setAttributeInternal(NOTES, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IsAttached.
     * @return the IsAttached
     */
    public Boolean getIsAttached() {
        return (Boolean) getAttributeInternal(ISATTACHED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IsAttached.
     * @param value value to set the  IsAttached
     */
    public void setIsAttached(Boolean value) {
        setAttributeInternal(ISATTACHED, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TimeSheetAttachmentsVO.
     */
    public RowIterator getTimeSheetAttachmentsVO() {
        return (RowIterator) getAttributeInternal(TIMESHEETATTACHMENTSVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TimeSheetTasksVO1.
     */
    public RowSet getTimeSheetTasksVO1() {
        return (RowSet) getAttributeInternal(TIMESHEETTASKSVO1);
    }
}

