package model.vo;

import java.math.BigDecimal;

import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 22 11:37:55 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TimeSheetRolesVORowImpl extends ViewRowImpl {
    public static final int ENTITY_TIMESHEETROLESEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        RoleId,
        Role,
        Description,
        TimeSheetUsersVO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ROLEID = AttributesEnum.RoleId.index();
    public static final int ROLE = AttributesEnum.Role.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int TIMESHEETUSERSVO = AttributesEnum.TimeSheetUsersVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TimeSheetRolesVORowImpl() {
    }

    /**
     * Gets TimeSheetRolesEO entity object.
     * @return the TimeSheetRolesEO
     */
    public EntityImpl getTimeSheetRolesEO() {
        return (EntityImpl) getEntity(ENTITY_TIMESHEETROLESEO);
    }

    /**
     * Gets the attribute value for ROLE_ID using the alias name RoleId.
     * @return the ROLE_ID
     */
    public BigDecimal getRoleId() {
        return (BigDecimal) getAttributeInternal(ROLEID);
    }

    /**
     * Sets <code>value</code> as attribute value for ROLE_ID using the alias name RoleId.
     * @param value value to set the ROLE_ID
     */
    public void setRoleId(BigDecimal value) {
        setAttributeInternal(ROLEID, value);
    }

    /**
     * Gets the attribute value for ROLE using the alias name Role.
     * @return the ROLE
     */
    public String getRole() {
        return (String) getAttributeInternal(ROLE);
    }

    /**
     * Sets <code>value</code> as attribute value for ROLE using the alias name Role.
     * @param value value to set the ROLE
     */
    public void setRole(String value) {
        setAttributeInternal(ROLE, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TimeSheetUsersVO.
     */
    public RowIterator getTimeSheetUsersVO() {
        return (RowIterator) getAttributeInternal(TIMESHEETUSERSVO);
    }
}

