package model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 22 11:37:57 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TimeSheetRolesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TimeSheetRolesVOImpl() {
    }
}

