package model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 17 12:02:19 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TimesheetUsersMappingVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TimesheetUsersMappingVOImpl() {
    }
}

