package model.vo;

import java.math.BigDecimal;

import model.eo.TimeSheetTasksEOImpl;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 22 13:09:08 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TimeSheetTasksVORowImpl extends ViewRowImpl {
    public static final int ENTITY_TIMESHEETTASKSEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        TaskId,
        Task,
        TaskDesc;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int TASKID = AttributesEnum.TaskId.index();
    public static final int TASK = AttributesEnum.Task.index();
    public static final int TASKDESC = AttributesEnum.TaskDesc.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TimeSheetTasksVORowImpl() {
    }

    /**
     * Gets TimeSheetTasksEO entity object.
     * @return the TimeSheetTasksEO
     */
    public TimeSheetTasksEOImpl getTimeSheetTasksEO() {
        return (TimeSheetTasksEOImpl) getEntity(ENTITY_TIMESHEETTASKSEO);
    }

    /**
     * Gets the attribute value for TASK_ID using the alias name TaskId.
     * @return the TASK_ID
     */
    public BigDecimal getTaskId() {
        return (BigDecimal) getAttributeInternal(TASKID);
    }

    /**
     * Sets <code>value</code> as attribute value for TASK_ID using the alias name TaskId.
     * @param value value to set the TASK_ID
     */
    public void setTaskId(BigDecimal value) {
        setAttributeInternal(TASKID, value);
    }

    /**
     * Gets the attribute value for TASK using the alias name Task.
     * @return the TASK
     */
    public String getTask() {
        return (String) getAttributeInternal(TASK);
    }

    /**
     * Sets <code>value</code> as attribute value for TASK using the alias name Task.
     * @param value value to set the TASK
     */
    public void setTask(String value) {
        setAttributeInternal(TASK, value);
    }

    /**
     * Gets the attribute value for TASK_DESC using the alias name TaskDesc.
     * @return the TASK_DESC
     */
    public String getTaskDesc() {
        return (String) getAttributeInternal(TASKDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for TASK_DESC using the alias name TaskDesc.
     * @param value value to set the TASK_DESC
     */
    public void setTaskDesc(String value) {
        setAttributeInternal(TASKDESC, value);
    }
}

