package model.vo;

import java.math.BigDecimal;

import model.eo.TimeSheetUsersEOImpl;

import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 21 17:12:25 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TimeSheetUsersVORowImpl extends ViewRowImpl {


    public static final int ENTITY_TIMESHEETUSERSEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        UserEmailId,
        CompanyName,
        Password,
        RoleId,
        UserId,
        ManagerId,
        UserName,
        TimeSheetRolesVO1,
        TimeSheetUsersVO1,
        TimeSheetUsersVO2,
        TimeSheetUsersVO3;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int USEREMAILID = AttributesEnum.UserEmailId.index();
    public static final int COMPANYNAME = AttributesEnum.CompanyName.index();
    public static final int PASSWORD = AttributesEnum.Password.index();
    public static final int ROLEID = AttributesEnum.RoleId.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int MANAGERID = AttributesEnum.ManagerId.index();
    public static final int USERNAME = AttributesEnum.UserName.index();
    public static final int TIMESHEETROLESVO1 = AttributesEnum.TimeSheetRolesVO1.index();
    public static final int TIMESHEETUSERSVO1 = AttributesEnum.TimeSheetUsersVO1.index();
    public static final int TIMESHEETUSERSVO2 = AttributesEnum.TimeSheetUsersVO2.index();
    public static final int TIMESHEETUSERSVO3 = AttributesEnum.TimeSheetUsersVO3.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TimeSheetUsersVORowImpl() {
    }

    /**
     * Gets TimeSheetUsersEO entity object.
     * @return the TimeSheetUsersEO
     */
    public TimeSheetUsersEOImpl getTimeSheetUsersEO() {
        return (TimeSheetUsersEOImpl) getEntity(ENTITY_TIMESHEETUSERSEO);
    }

    /**
     * Gets the attribute value for USER_EMAIL_ID using the alias name UserEmailId.
     * @return the USER_EMAIL_ID
     */
    public String getUserEmailId() {
        return (String) getAttributeInternal(USEREMAILID);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_EMAIL_ID using the alias name UserEmailId.
     * @param value value to set the USER_EMAIL_ID
     */
    public void setUserEmailId(String value) {
        setAttributeInternal(USEREMAILID, value);
    }

    /**
     * Gets the attribute value for COMPANY_NAME using the alias name CompanyName.
     * @return the COMPANY_NAME
     */
    public String getCompanyName() {
        return (String) getAttributeInternal(COMPANYNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_NAME using the alias name CompanyName.
     * @param value value to set the COMPANY_NAME
     */
    public void setCompanyName(String value) {
        setAttributeInternal(COMPANYNAME, value);
    }

    /**
     * Gets the attribute value for PASSWORD using the alias name Password.
     * @return the PASSWORD
     */
    public String getPassword() {
        return (String) getAttributeInternal(PASSWORD);
    }

    /**
     * Sets <code>value</code> as attribute value for PASSWORD using the alias name Password.
     * @param value value to set the PASSWORD
     */
    public void setPassword(String value) {
        setAttributeInternal(PASSWORD, value);
    }

    /**
     * Gets the attribute value for ROLE_ID using the alias name RoleId.
     * @return the ROLE_ID
     */
    public BigDecimal getRoleId() {
        return (BigDecimal) getAttributeInternal(ROLEID);
    }

    /**
     * Sets <code>value</code> as attribute value for ROLE_ID using the alias name RoleId.
     * @param value value to set the ROLE_ID
     */
    public void setRoleId(BigDecimal value) {
        setAttributeInternal(ROLEID, value);
    }

    /**
     * Gets the attribute value for USER_ID using the alias name UserId.
     * @return the USER_ID
     */
    public BigDecimal getUserId() {
        return (BigDecimal) getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_ID using the alias name UserId.
     * @param value value to set the USER_ID
     */
    public void setUserId(BigDecimal value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for MANAGER_ID using the alias name ManagerId.
     * @return the MANAGER_ID
     */
    public BigDecimal getManagerId() {
        return (BigDecimal) getAttributeInternal(MANAGERID);
    }

    /**
     * Sets <code>value</code> as attribute value for MANAGER_ID using the alias name ManagerId.
     * @param value value to set the MANAGER_ID
     */
    public void setManagerId(BigDecimal value) {
        setAttributeInternal(MANAGERID, value);
    }

    /**
     * Gets the attribute value for USER_NAME using the alias name UserName.
     * @return the USER_NAME
     */
    public String getUserName() {
        return (String) getAttributeInternal(USERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_NAME using the alias name UserName.
     * @param value value to set the USER_NAME
     */
    public void setUserName(String value) {
        setAttributeInternal(USERNAME, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TimeSheetRolesVO1.
     */
    public RowSet getTimeSheetRolesVO1() {
        return (RowSet) getAttributeInternal(TIMESHEETROLESVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TimeSheetUsersVO1.
     */
    public RowSet getTimeSheetUsersVO1() {
        return (RowSet) getAttributeInternal(TIMESHEETUSERSVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TimeSheetUsersVO2.
     */
    public RowSet getTimeSheetUsersVO2() {
        return (RowSet) getAttributeInternal(TIMESHEETUSERSVO2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TimeSheetUsersVO3.
     */
    public RowSet getTimeSheetUsersVO3() {
        return (RowSet) getAttributeInternal(TIMESHEETUSERSVO3);
    }
}

