package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import model.eo.TimeSheetWeekEOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.BFileDomain;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 14 12:01:12 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TimeSheetWeekVORowImpl extends ViewRowImpl {


    public static final int ENTITY_TIMESHEETWEEKEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        TimeSheetId,
        WeekStartDate,
        WeekEndDate,
        TotalHours,
        TotalExpences,
        ApproverComments,
        UserId,
        Status,
        SubmittedBy,
        SubmittedTs,
        ApprovedTs,
        ApprovedBy,
        TaskId,
        TimeSheetWeekHoursVO,
        TimeSheetDaysVO,
        TSUSERSVVO1,
        TSUSERSVVO2;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int TIMESHEETID = AttributesEnum.TimeSheetId.index();
    public static final int WEEKSTARTDATE = AttributesEnum.WeekStartDate.index();
    public static final int WEEKENDDATE = AttributesEnum.WeekEndDate.index();
    public static final int TOTALHOURS = AttributesEnum.TotalHours.index();
    public static final int TOTALEXPENCES = AttributesEnum.TotalExpences.index();
    public static final int APPROVERCOMMENTS = AttributesEnum.ApproverComments.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int SUBMITTEDBY = AttributesEnum.SubmittedBy.index();
    public static final int SUBMITTEDTS = AttributesEnum.SubmittedTs.index();
    public static final int APPROVEDTS = AttributesEnum.ApprovedTs.index();
    public static final int APPROVEDBY = AttributesEnum.ApprovedBy.index();
    public static final int TASKID = AttributesEnum.TaskId.index();
    public static final int TIMESHEETWEEKHOURSVO = AttributesEnum.TimeSheetWeekHoursVO.index();
    public static final int TIMESHEETDAYSVO = AttributesEnum.TimeSheetDaysVO.index();
    public static final int TSUSERSVVO1 = AttributesEnum.TSUSERSVVO1.index();
    public static final int TSUSERSVVO2 = AttributesEnum.TSUSERSVVO2.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TimeSheetWeekVORowImpl() {
    }

    /**
     * Gets TimeSheetWeekEO entity object.
     * @return the TimeSheetWeekEO
     */
    public TimeSheetWeekEOImpl getTimeSheetWeekEO() {
        return (TimeSheetWeekEOImpl) getEntity(ENTITY_TIMESHEETWEEKEO);
    }

    /**
     * Gets the attribute value for TIME_SHEET_ID using the alias name TimeSheetId.
     * @return the TIME_SHEET_ID
     */
    public BigDecimal getTimeSheetId() {
        return (BigDecimal) getAttributeInternal(TIMESHEETID);
    }

    /**
     * Sets <code>value</code> as attribute value for TIME_SHEET_ID using the alias name TimeSheetId.
     * @param value value to set the TIME_SHEET_ID
     */
    public void setTimeSheetId(BigDecimal value) {
        setAttributeInternal(TIMESHEETID, value);
    }

    /**
     * Gets the attribute value for WEEK_START_DATE using the alias name WeekStartDate.
     * @return the WEEK_START_DATE
     */
    public Timestamp getWeekStartDate() {
        return (Timestamp) getAttributeInternal(WEEKSTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for WEEK_START_DATE using the alias name WeekStartDate.
     * @param value value to set the WEEK_START_DATE
     */
    public void setWeekStartDate(Timestamp value) {
        setAttributeInternal(WEEKSTARTDATE, value);
    }

    /**
     * Gets the attribute value for WEEK_END_DATE using the alias name WeekEndDate.
     * @return the WEEK_END_DATE
     */
    public Timestamp getWeekEndDate() {
        return (Timestamp) getAttributeInternal(WEEKENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for WEEK_END_DATE using the alias name WeekEndDate.
     * @param value value to set the WEEK_END_DATE
     */
    public void setWeekEndDate(Timestamp value) {
        setAttributeInternal(WEEKENDDATE, value);
    }

    /**
     * Gets the attribute value for TOTAL_HOURS using the alias name TotalHours.
     * @return the TOTAL_HOURS
     */
    public Integer getTotalHours() {
        return (Integer) getAttributeInternal(TOTALHOURS);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_HOURS using the alias name TotalHours.
     * @param value value to set the TOTAL_HOURS
     */
    public void setTotalHours(Integer value) {
        setAttributeInternal(TOTALHOURS, value);
    }

    /**
     * Gets the attribute value for TOTAL_EXPENCES using the alias name TotalExpences.
     * @return the TOTAL_EXPENCES
     */
    public BigDecimal getTotalExpences() {
        return (BigDecimal) getAttributeInternal(TOTALEXPENCES);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_EXPENCES using the alias name TotalExpences.
     * @param value value to set the TOTAL_EXPENCES
     */
    public void setTotalExpences(BigDecimal value) {
        setAttributeInternal(TOTALEXPENCES, value);
    }

    /**
     * Gets the attribute value for APPROVER_COMMENTS using the alias name ApproverComments.
     * @return the APPROVER_COMMENTS
     */
    public String getApproverComments() {
        return (String) getAttributeInternal(APPROVERCOMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVER_COMMENTS using the alias name ApproverComments.
     * @param value value to set the APPROVER_COMMENTS
     */
    public void setApproverComments(String value) {
        setAttributeInternal(APPROVERCOMMENTS, value);
    }

    /**
     * Gets the attribute value for USER_ID using the alias name UserId.
     * @return the USER_ID
     */
    public BigDecimal getUserId() {
        return (BigDecimal) getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_ID using the alias name UserId.
     * @param value value to set the USER_ID
     */
    public void setUserId(BigDecimal value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for SUBMITTED_BY using the alias name SubmittedBy.
     * @return the SUBMITTED_BY
     */
    public BigDecimal getSubmittedBy() {
        return (BigDecimal) getAttributeInternal(SUBMITTEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBMITTED_BY using the alias name SubmittedBy.
     * @param value value to set the SUBMITTED_BY
     */
    public void setSubmittedBy(BigDecimal value) {
        setAttributeInternal(SUBMITTEDBY, value);
    }

    /**
     * Gets the attribute value for SUBMITTED_TS using the alias name SubmittedTs.
     * @return the SUBMITTED_TS
     */
    public Timestamp getSubmittedTs() {
        return (Timestamp) getAttributeInternal(SUBMITTEDTS);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBMITTED_TS using the alias name SubmittedTs.
     * @param value value to set the SUBMITTED_TS
     */
    public void setSubmittedTs(Timestamp value) {
        setAttributeInternal(SUBMITTEDTS, value);
    }

    /**
     * Gets the attribute value for APPROVED_TS using the alias name ApprovedTs.
     * @return the APPROVED_TS
     */
    public Timestamp getApprovedTs() {
        return (Timestamp) getAttributeInternal(APPROVEDTS);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVED_TS using the alias name ApprovedTs.
     * @param value value to set the APPROVED_TS
     */
    public void setApprovedTs(Timestamp value) {
        setAttributeInternal(APPROVEDTS, value);
    }

    /**
     * Gets the attribute value for APPROVED_BY using the alias name ApprovedBy.
     * @return the APPROVED_BY
     */
    public BigDecimal getApprovedBy() {
        return (BigDecimal) getAttributeInternal(APPROVEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVED_BY using the alias name ApprovedBy.
     * @param value value to set the APPROVED_BY
     */
    public void setApprovedBy(BigDecimal value) {
        setAttributeInternal(APPROVEDBY, value);
    }


    /**
     * Gets the attribute value for TASK_ID using the alias name TaskId.
     * @return the TASK_ID
     */
    public BigDecimal getTaskId() {
        return (BigDecimal) getAttributeInternal(TASKID);
    }

    /**
     * Sets <code>value</code> as attribute value for TASK_ID using the alias name TaskId.
     * @param value value to set the TASK_ID
     */
    public void setTaskId(BigDecimal value) {
        setAttributeInternal(TASKID, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TimeSheetWeekHoursVO.
     */
    public RowIterator getTimeSheetWeekHoursVO() {
        return (RowIterator) getAttributeInternal(TIMESHEETWEEKHOURSVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TimeSheetDaysVO.
     */
    public RowIterator getTimeSheetDaysVO() {
        return (RowIterator) getAttributeInternal(TIMESHEETDAYSVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TSUSERSVVO1.
     */
    public RowSet getTSUSERSVVO1() {
        return (RowSet) getAttributeInternal(TSUSERSVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TSUSERSVVO2.
     */
    public RowSet getTSUSERSVVO2() {
        return (RowSet) getAttributeInternal(TSUSERSVVO2);
    }

}

