package model.vo;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 14 11:22:40 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WeeksVVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        GivenDate,
        EndDate,
        WkStarts,
        WkEnds,
        Week,
        WkNumber,
        CalcStartDate;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int GIVENDATE = AttributesEnum.GivenDate.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int WKSTARTS = AttributesEnum.WkStarts.index();
    public static final int WKENDS = AttributesEnum.WkEnds.index();
    public static final int WEEK = AttributesEnum.Week.index();
    public static final int WKNUMBER = AttributesEnum.WkNumber.index();
    public static final int CALCSTARTDATE = AttributesEnum.CalcStartDate.index();

    /**
     * This is the default constructor (do not remove).
     */
    public WeeksVVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute GivenDate.
     * @return the GivenDate
     */
    public Timestamp getGivenDate() {
        return (Timestamp) getAttributeInternal(GIVENDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute EndDate.
     * @return the EndDate
     */
    public Timestamp getEndDate() {
        return (Timestamp) getAttributeInternal(ENDDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute WkStarts.
     * @return the WkStarts
     */
    public Timestamp getWkStarts() {
        return (Timestamp) getAttributeInternal(WKSTARTS);
    }

    /**
     * Gets the attribute value for the calculated attribute WkEnds.
     * @return the WkEnds
     */
    public Timestamp getWkEnds() {
        return (Timestamp) getAttributeInternal(WKENDS);
    }

    /**
     * Gets the attribute value for the calculated attribute Week.
     * @return the Week
     */
    public String getWeek() {
        return (String) getAttributeInternal(WEEK);
    }

    /**
     * Gets the attribute value for the calculated attribute WkNumber.
     * @return the WkNumber
     */
    public String getWkNumber() {
        return (String) getAttributeInternal(WKNUMBER);
    }

    /**
     * Gets the attribute value for the calculated attribute CalcStartDate.
     * @return the CalcStartDate
     */
    public Timestamp getCalcStartDate() {
        return (Timestamp) getAttributeInternal(CALCSTARTDATE);
    }
}

