package model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 14 11:22:41 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WeeksVVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public WeeksVVOImpl() {
    }

    /**
     * Returns the bind variable value for systemdate.
     * @return bind variable value for systemdate
     */
    public String getsystemdate() {
        return (String) getNamedWhereClauseParam("systemdate");
    }

    /**
     * Sets <code>value</code> for bind variable systemdate.
     * @param value value to bind as systemdate
     */
    public void setsystemdate(String value) {
        setNamedWhereClauseParam("systemdate", value);
    }
}

