package model.am.common;

import java.math.BigDecimal;

import java.util.ArrayList;

import java.util.Date;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 14 12:23:27 IST 2016
// ---------------------------------------------------------------------
public interface TimeSheetAppController extends ApplicationModule {
    ArrayList getWeekList(Date systemDate);


    BigDecimal initTimeSheet(Date currentDate);

    void addTimeSheetHours(BigDecimal timeSheetId);

    void editTimeSheetHours(BigDecimal timeSheetId);

    void submitForApproval(BigDecimal timeSheetId);

    Boolean deleteTimeSheetHours(BigDecimal timeSheetId);
}

