package model.am.common;

import java.math.BigDecimal;

import java.util.ArrayList;

import java.util.Date;

import oracle.jbo.ApplicationModule;
import oracle.jbo.domain.BlobDomain;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 14 12:23:27 IST 2016
// ---------------------------------------------------------------------
public interface TimeSheetAppController extends ApplicationModule {
    ArrayList getWeekList(Date systemDate);


    BigDecimal initTimeSheet(Date currentDate);

    void addTimeSheetHours(BigDecimal timeSheetId);

    void editTimeSheetHours(BigDecimal timeSheetId);

    void submitForApproval(BigDecimal timeSheetId);

    Boolean deleteTimeSheetHours(BigDecimal timeSheetId);

    void approveTimeSheet(BigDecimal timeSheetID, String comments);

    void rejectTimeSheet(BigDecimal timeSheetID, String comments);

    void saveUsers(BigDecimal userId);

    void createUsers();

    void createRoles();

    void saveRoles(BigDecimal roleId);

    Boolean deleteTimeSheetRoles();

    void save();

    void cancel();

    void createTasks();

    void saveTasks(BigDecimal taskId);

    Boolean deleteTimeSheetTasks();

    Boolean deleteTimeSheetUsers();

    void unSubmitTimeSheet(BigDecimal timeSheetId);

    void createTimeSheet(Date currentDate);

    void uploadFile(String fileName, String contentType, BlobDomain file);

    void initSubmittedTS(String status);

    void updatePassword(String userName,String password);

    void saveRoleChange(BigDecimal userId, BigDecimal roleId);

    void saveTimeSheet(BigDecimal timeSheetId);

    void createNewTimeSheet(Date currentDate);

    void ViewAllTs();

    void getAttachments();

    void getUsersList();

    void saveUserChange();
}

