package model.eo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 18 15:05:22 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RecCandidateInfoEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CandidateId,
        FirstName,
        LastName,
        MiddleName,
        Dob,
        Gender,
        EmailId,
        MobileNo,
        LandlineNo,
        Address,
        Pin,
        City,
        State,
        Relocate,
        Travel,
        ReasonsForChange,
        Status,
        CreatedBy,
        CreatedOn,
        UpdatedBy,
        UpdatedOn,
        RecEduInfoEO,
        RecExpInfoEO,
        RecReferralInfoEO,
        RecReferencesInfoEO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CANDIDATEID = AttributesEnum.CandidateId.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int MIDDLENAME = AttributesEnum.MiddleName.index();
    public static final int DOB = AttributesEnum.Dob.index();
    public static final int GENDER = AttributesEnum.Gender.index();
    public static final int EMAILID = AttributesEnum.EmailId.index();
    public static final int MOBILENO = AttributesEnum.MobileNo.index();
    public static final int LANDLINENO = AttributesEnum.LandlineNo.index();
    public static final int ADDRESS = AttributesEnum.Address.index();
    public static final int PIN = AttributesEnum.Pin.index();
    public static final int CITY = AttributesEnum.City.index();
    public static final int STATE = AttributesEnum.State.index();
    public static final int RELOCATE = AttributesEnum.Relocate.index();
    public static final int TRAVEL = AttributesEnum.Travel.index();
    public static final int REASONSFORCHANGE = AttributesEnum.ReasonsForChange.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDON = AttributesEnum.CreatedOn.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDON = AttributesEnum.UpdatedOn.index();
    public static final int RECEDUINFOEO = AttributesEnum.RecEduInfoEO.index();
    public static final int RECEXPINFOEO = AttributesEnum.RecExpInfoEO.index();
    public static final int RECREFERRALINFOEO = AttributesEnum.RecReferralInfoEO.index();
    public static final int RECREFERENCESINFOEO = AttributesEnum.RecReferencesInfoEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RecCandidateInfoEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.eo.RecCandidateInfoEO");
    }


    /**
     * Gets the attribute value for CandidateId, using the alias name CandidateId.
     * @return the value of CandidateId
     */
    public BigDecimal getCandidateId() {
        return (BigDecimal) getAttributeInternal(CANDIDATEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CandidateId.
     * @param value value to set the CandidateId
     */
    public void setCandidateId(BigDecimal value) {
        setAttributeInternal(CANDIDATEID, value);
    }

    /**
     * Gets the attribute value for FirstName, using the alias name FirstName.
     * @return the value of FirstName
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for FirstName.
     * @param value value to set the FirstName
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**
     * Gets the attribute value for LastName, using the alias name LastName.
     * @return the value of LastName
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastName.
     * @param value value to set the LastName
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**
     * Gets the attribute value for MiddleName, using the alias name MiddleName.
     * @return the value of MiddleName
     */
    public String getMiddleName() {
        return (String) getAttributeInternal(MIDDLENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for MiddleName.
     * @param value value to set the MiddleName
     */
    public void setMiddleName(String value) {
        setAttributeInternal(MIDDLENAME, value);
    }

    /**
     * Gets the attribute value for Dob, using the alias name Dob.
     * @return the value of Dob
     */
    public Timestamp getDob() {
        return (Timestamp) getAttributeInternal(DOB);
    }

    /**
     * Sets <code>value</code> as the attribute value for Dob.
     * @param value value to set the Dob
     */
    public void setDob(Timestamp value) {
        setAttributeInternal(DOB, value);
    }

    /**
     * Gets the attribute value for Gender, using the alias name Gender.
     * @return the value of Gender
     */
    public String getGender() {
        return (String) getAttributeInternal(GENDER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Gender.
     * @param value value to set the Gender
     */
    public void setGender(String value) {
        setAttributeInternal(GENDER, value);
    }

    /**
     * Gets the attribute value for EmailId, using the alias name EmailId.
     * @return the value of EmailId
     */
    public String getEmailId() {
        return (String) getAttributeInternal(EMAILID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmailId.
     * @param value value to set the EmailId
     */
    public void setEmailId(String value) {
        setAttributeInternal(EMAILID, value);
    }

    /**
     * Gets the attribute value for MobileNo, using the alias name MobileNo.
     * @return the value of MobileNo
     */
    public Long getMobileNo() {
        return (Long) getAttributeInternal(MOBILENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for MobileNo.
     * @param value value to set the MobileNo
     */
    public void setMobileNo(Long value) {
        setAttributeInternal(MOBILENO, value);
    }

    /**
     * Gets the attribute value for LandlineNo, using the alias name LandlineNo.
     * @return the value of LandlineNo
     */
    public Long getLandlineNo() {
        return (Long) getAttributeInternal(LANDLINENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for LandlineNo.
     * @param value value to set the LandlineNo
     */
    public void setLandlineNo(Long value) {
        setAttributeInternal(LANDLINENO, value);
    }

    /**
     * Gets the attribute value for Address, using the alias name Address.
     * @return the value of Address
     */
    public String getAddress() {
        return (String) getAttributeInternal(ADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Address.
     * @param value value to set the Address
     */
    public void setAddress(String value) {
        setAttributeInternal(ADDRESS, value);
    }

    /**
     * Gets the attribute value for Pin, using the alias name Pin.
     * @return the value of Pin
     */
    public Integer getPin() {
        return (Integer) getAttributeInternal(PIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for Pin.
     * @param value value to set the Pin
     */
    public void setPin(Integer value) {
        setAttributeInternal(PIN, value);
    }

    /**
     * Gets the attribute value for City, using the alias name City.
     * @return the value of City
     */
    public Integer getCity() {
        return (Integer) getAttributeInternal(CITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for City.
     * @param value value to set the City
     */
    public void setCity(Integer value) {
        setAttributeInternal(CITY, value);
    }

    /**
     * Gets the attribute value for State, using the alias name State.
     * @return the value of State
     */
    public Integer getState() {
        return (Integer) getAttributeInternal(STATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for State.
     * @param value value to set the State
     */
    public void setState(Integer value) {
        setAttributeInternal(STATE, value);
    }

    /**
     * Gets the attribute value for Relocate, using the alias name Relocate.
     * @return the value of Relocate
     */
    public String getRelocate() {
        return (String) getAttributeInternal(RELOCATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Relocate.
     * @param value value to set the Relocate
     */
    public void setRelocate(String value) {
        setAttributeInternal(RELOCATE, value);
    }

    /**
     * Gets the attribute value for Travel, using the alias name Travel.
     * @return the value of Travel
     */
    public String getTravel() {
        return (String) getAttributeInternal(TRAVEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Travel.
     * @param value value to set the Travel
     */
    public void setTravel(String value) {
        setAttributeInternal(TRAVEL, value);
    }

    /**
     * Gets the attribute value for ReasonsForChange, using the alias name ReasonsForChange.
     * @return the value of ReasonsForChange
     */
    public String getReasonsForChange() {
        return (String) getAttributeInternal(REASONSFORCHANGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReasonsForChange.
     * @param value value to set the ReasonsForChange
     */
    public void setReasonsForChange(String value) {
        setAttributeInternal(REASONSFORCHANGE, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the value of Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }


    /**
     * Gets the attribute value for CreatedOn, using the alias name CreatedOn.
     * @return the value of CreatedOn
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) getAttributeInternal(CREATEDON);
    }


    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public String getUpdatedBy() {
        return (String) getAttributeInternal(UPDATEDBY);
    }


    /**
     * Gets the attribute value for UpdatedOn, using the alias name UpdatedOn.
     * @return the value of UpdatedOn
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) getAttributeInternal(UPDATEDON);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getRecEduInfoEO() {
        return (RowIterator) getAttributeInternal(RECEDUINFOEO);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getRecExpInfoEO() {
        return (RowIterator) getAttributeInternal(RECEXPINFOEO);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getRecReferralInfoEO() {
        return (RowIterator) getAttributeInternal(RECREFERRALINFOEO);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getRecReferencesInfoEO() {
        return (RowIterator) getAttributeInternal(RECREFERENCESINFOEO);
    }


    /**
     * @param candidateId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal candidateId) {
        return new Key(new Object[] { candidateId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }
}

