package model.eo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 18 15:06:55 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RecEduInfoEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        EduId,
        CandidatenId,
        QalificationId,
        InstituteName,
        YearOfCompletion,
        Percentage,
        CreatedBy,
        CreatedOn,
        UpdatedBy,
        UpdatedOn,
        RecCandidateInfoEO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int EDUID = AttributesEnum.EduId.index();
    public static final int CANDIDATENID = AttributesEnum.CandidatenId.index();
    public static final int QALIFICATIONID = AttributesEnum.QalificationId.index();
    public static final int INSTITUTENAME = AttributesEnum.InstituteName.index();
    public static final int YEAROFCOMPLETION = AttributesEnum.YearOfCompletion.index();
    public static final int PERCENTAGE = AttributesEnum.Percentage.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDON = AttributesEnum.CreatedOn.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDON = AttributesEnum.UpdatedOn.index();
    public static final int RECCANDIDATEINFOEO = AttributesEnum.RecCandidateInfoEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RecEduInfoEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.eo.RecEduInfoEO");
    }


    /**
     * Gets the attribute value for EduId, using the alias name EduId.
     * @return the value of EduId
     */
    public BigDecimal getEduId() {
        return (BigDecimal) getAttributeInternal(EDUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EduId.
     * @param value value to set the EduId
     */
    public void setEduId(BigDecimal value) {
        setAttributeInternal(EDUID, value);
    }

    /**
     * Gets the attribute value for CandidatenId, using the alias name CandidatenId.
     * @return the value of CandidatenId
     */
    public BigDecimal getCandidatenId() {
        return (BigDecimal) getAttributeInternal(CANDIDATENID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CandidatenId.
     * @param value value to set the CandidatenId
     */
    public void setCandidatenId(BigDecimal value) {
        setAttributeInternal(CANDIDATENID, value);
    }

    /**
     * Gets the attribute value for QalificationId, using the alias name QalificationId.
     * @return the value of QalificationId
     */
    public BigDecimal getQalificationId() {
        return (BigDecimal) getAttributeInternal(QALIFICATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for QalificationId.
     * @param value value to set the QalificationId
     */
    public void setQalificationId(BigDecimal value) {
        setAttributeInternal(QALIFICATIONID, value);
    }

    /**
     * Gets the attribute value for InstituteName, using the alias name InstituteName.
     * @return the value of InstituteName
     */
    public String getInstituteName() {
        return (String) getAttributeInternal(INSTITUTENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for InstituteName.
     * @param value value to set the InstituteName
     */
    public void setInstituteName(String value) {
        setAttributeInternal(INSTITUTENAME, value);
    }

    /**
     * Gets the attribute value for YearOfCompletion, using the alias name YearOfCompletion.
     * @return the value of YearOfCompletion
     */
    public Integer getYearOfCompletion() {
        return (Integer) getAttributeInternal(YEAROFCOMPLETION);
    }

    /**
     * Sets <code>value</code> as the attribute value for YearOfCompletion.
     * @param value value to set the YearOfCompletion
     */
    public void setYearOfCompletion(Integer value) {
        setAttributeInternal(YEAROFCOMPLETION, value);
    }

    /**
     * Gets the attribute value for Percentage, using the alias name Percentage.
     * @return the value of Percentage
     */
    public String getPercentage() {
        return (String) getAttributeInternal(PERCENTAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Percentage.
     * @param value value to set the Percentage
     */
    public void setPercentage(String value) {
        setAttributeInternal(PERCENTAGE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }


    /**
     * Gets the attribute value for CreatedOn, using the alias name CreatedOn.
     * @return the value of CreatedOn
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) getAttributeInternal(CREATEDON);
    }


    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public String getUpdatedBy() {
        return (String) getAttributeInternal(UPDATEDBY);
    }


    /**
     * Gets the attribute value for UpdatedOn, using the alias name UpdatedOn.
     * @return the value of UpdatedOn
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) getAttributeInternal(UPDATEDON);
    }


    /**
     * @return the associated entity RecCandidateInfoEOImpl.
     */
    public RecCandidateInfoEOImpl getRecCandidateInfoEO() {
        return (RecCandidateInfoEOImpl) getAttributeInternal(RECCANDIDATEINFOEO);
    }

    /**
     * Sets <code>value</code> as the associated entity RecCandidateInfoEOImpl.
     */
    public void setRecCandidateInfoEO(RecCandidateInfoEOImpl value) {
        setAttributeInternal(RECCANDIDATEINFOEO, value);
    }


    /**
     * @param eduId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal eduId) {
        return new Key(new Object[] { eduId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }
}

