package model.eo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 18 15:07:43 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RecExpInfoEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ExpId,
        CandidateId,
        CompanyName,
        Title,
        ReasonsForLeaving,
        CreatedBy,
        CreatedOn,
        UpdatedBy,
        UpdatedOn,
        RecCandidateInfoEO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int EXPID = AttributesEnum.ExpId.index();
    public static final int CANDIDATEID = AttributesEnum.CandidateId.index();
    public static final int COMPANYNAME = AttributesEnum.CompanyName.index();
    public static final int TITLE = AttributesEnum.Title.index();
    public static final int REASONSFORLEAVING = AttributesEnum.ReasonsForLeaving.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDON = AttributesEnum.CreatedOn.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDON = AttributesEnum.UpdatedOn.index();
    public static final int RECCANDIDATEINFOEO = AttributesEnum.RecCandidateInfoEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RecExpInfoEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.eo.RecExpInfoEO");
    }


    /**
     * Gets the attribute value for ExpId, using the alias name ExpId.
     * @return the value of ExpId
     */
    public BigDecimal getExpId() {
        return (BigDecimal) getAttributeInternal(EXPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpId.
     * @param value value to set the ExpId
     */
    public void setExpId(BigDecimal value) {
        setAttributeInternal(EXPID, value);
    }

    /**
     * Gets the attribute value for CandidateId, using the alias name CandidateId.
     * @return the value of CandidateId
     */
    public BigDecimal getCandidateId() {
        return (BigDecimal) getAttributeInternal(CANDIDATEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CandidateId.
     * @param value value to set the CandidateId
     */
    public void setCandidateId(BigDecimal value) {
        setAttributeInternal(CANDIDATEID, value);
    }

    /**
     * Gets the attribute value for CompanyName, using the alias name CompanyName.
     * @return the value of CompanyName
     */
    public String getCompanyName() {
        return (String) getAttributeInternal(COMPANYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyName.
     * @param value value to set the CompanyName
     */
    public void setCompanyName(String value) {
        setAttributeInternal(COMPANYNAME, value);
    }

    /**
     * Gets the attribute value for Title, using the alias name Title.
     * @return the value of Title
     */
    public String getTitle() {
        return (String) getAttributeInternal(TITLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Title.
     * @param value value to set the Title
     */
    public void setTitle(String value) {
        setAttributeInternal(TITLE, value);
    }

    /**
     * Gets the attribute value for ReasonsForLeaving, using the alias name ReasonsForLeaving.
     * @return the value of ReasonsForLeaving
     */
    public String getReasonsForLeaving() {
        return (String) getAttributeInternal(REASONSFORLEAVING);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReasonsForLeaving.
     * @param value value to set the ReasonsForLeaving
     */
    public void setReasonsForLeaving(String value) {
        setAttributeInternal(REASONSFORLEAVING, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }


    /**
     * Gets the attribute value for CreatedOn, using the alias name CreatedOn.
     * @return the value of CreatedOn
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) getAttributeInternal(CREATEDON);
    }


    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public String getUpdatedBy() {
        return (String) getAttributeInternal(UPDATEDBY);
    }


    /**
     * Gets the attribute value for UpdatedOn, using the alias name UpdatedOn.
     * @return the value of UpdatedOn
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) getAttributeInternal(UPDATEDON);
    }


    /**
     * @return the associated entity RecCandidateInfoEOImpl.
     */
    public RecCandidateInfoEOImpl getRecCandidateInfoEO() {
        return (RecCandidateInfoEOImpl) getAttributeInternal(RECCANDIDATEINFOEO);
    }

    /**
     * Sets <code>value</code> as the associated entity RecCandidateInfoEOImpl.
     */
    public void setRecCandidateInfoEO(RecCandidateInfoEOImpl value) {
        setAttributeInternal(RECCANDIDATEINFOEO, value);
    }


    /**
     * @param expId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal expId) {
        return new Key(new Object[] { expId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }
}

