package model.eo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 18 15:07:54 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RecInterviewInfoEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        InterviewId,
        CandidateId,
        InterviewerId,
        Feedback,
        Description,
        Status,
        CreatedBy,
        CreatedOn,
        UpdatedBy,
        UpdatedOn;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int INTERVIEWID = AttributesEnum.InterviewId.index();
    public static final int CANDIDATEID = AttributesEnum.CandidateId.index();
    public static final int INTERVIEWERID = AttributesEnum.InterviewerId.index();
    public static final int FEEDBACK = AttributesEnum.Feedback.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDON = AttributesEnum.CreatedOn.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int UPDATEDON = AttributesEnum.UpdatedOn.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RecInterviewInfoEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.eo.RecInterviewInfoEO");
    }

    /**
     * Gets the attribute value for InterviewId, using the alias name InterviewId.
     * @return the value of InterviewId
     */
    public BigDecimal getInterviewId() {
        return (BigDecimal) getAttributeInternal(INTERVIEWID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InterviewId.
     * @param value value to set the InterviewId
     */
    public void setInterviewId(BigDecimal value) {
        setAttributeInternal(INTERVIEWID, value);
    }

    /**
     * Gets the attribute value for CandidateId, using the alias name CandidateId.
     * @return the value of CandidateId
     */
    public BigDecimal getCandidateId() {
        return (BigDecimal) getAttributeInternal(CANDIDATEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CandidateId.
     * @param value value to set the CandidateId
     */
    public void setCandidateId(BigDecimal value) {
        setAttributeInternal(CANDIDATEID, value);
    }

    /**
     * Gets the attribute value for InterviewerId, using the alias name InterviewerId.
     * @return the value of InterviewerId
     */
    public BigDecimal getInterviewerId() {
        return (BigDecimal) getAttributeInternal(INTERVIEWERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InterviewerId.
     * @param value value to set the InterviewerId
     */
    public void setInterviewerId(BigDecimal value) {
        setAttributeInternal(INTERVIEWERID, value);
    }

    /**
     * Gets the attribute value for Feedback, using the alias name Feedback.
     * @return the value of Feedback
     */
    public Timestamp getFeedback() {
        return (Timestamp) getAttributeInternal(FEEDBACK);
    }

    /**
     * Sets <code>value</code> as the attribute value for Feedback.
     * @param value value to set the Feedback
     */
    public void setFeedback(Timestamp value) {
        setAttributeInternal(FEEDBACK, value);
    }

    /**
     * Gets the attribute value for Description, using the alias name Description.
     * @return the value of Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Description.
     * @param value value to set the Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the value of Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedOn, using the alias name CreatedOn.
     * @return the value of CreatedOn
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) getAttributeInternal(CREATEDON);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedOn.
     * @param value value to set the CreatedOn
     */
    public void setCreatedOn(Timestamp value) {
        setAttributeInternal(CREATEDON, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the value of UpdatedBy
     */
    public String getUpdatedBy() {
        return (String) getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedOn, using the alias name UpdatedOn.
     * @return the value of UpdatedOn
     */
    public Timestamp getUpdatedOn() {
        return (Timestamp) getAttributeInternal(UPDATEDON);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedOn.
     * @param value value to set the UpdatedOn
     */
    public void setUpdatedOn(Timestamp value) {
        setAttributeInternal(UPDATEDON, value);
    }


    /**
     * @param interviewId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal interviewId) {
        return new Key(new Object[] { interviewId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }
}

