package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import model.eo.RecCandidateInfoEOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 18 16:13:28 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RecCandidateInfoVORowImpl extends ViewRowImpl {


    public static final int ENTITY_RECCANDIDATEINFOEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CandidateId,
        FirstName,
        LastName,
        MiddleName,
        Dob,
        Gender,
        EmailId,
        MobileNo,
        LandlineNo,
        Address,
        Pin,
        City,
        State,
        Relocate,
        Travel,
        ReasonsForChange,
        Status,
        RecEduInfoVO,
        RecExpInfoVO,
        RecReferralInfoVO,
        RecReferencesInfoVO,
        GenderCodes1,
        StatesVVO1,
        CitiesVVO1;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CANDIDATEID = AttributesEnum.CandidateId.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int MIDDLENAME = AttributesEnum.MiddleName.index();
    public static final int DOB = AttributesEnum.Dob.index();
    public static final int GENDER = AttributesEnum.Gender.index();
    public static final int EMAILID = AttributesEnum.EmailId.index();
    public static final int MOBILENO = AttributesEnum.MobileNo.index();
    public static final int LANDLINENO = AttributesEnum.LandlineNo.index();
    public static final int ADDRESS = AttributesEnum.Address.index();
    public static final int PIN = AttributesEnum.Pin.index();
    public static final int CITY = AttributesEnum.City.index();
    public static final int STATE = AttributesEnum.State.index();
    public static final int RELOCATE = AttributesEnum.Relocate.index();
    public static final int TRAVEL = AttributesEnum.Travel.index();
    public static final int REASONSFORCHANGE = AttributesEnum.ReasonsForChange.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int RECEDUINFOVO = AttributesEnum.RecEduInfoVO.index();
    public static final int RECEXPINFOVO = AttributesEnum.RecExpInfoVO.index();
    public static final int RECREFERRALINFOVO = AttributesEnum.RecReferralInfoVO.index();
    public static final int RECREFERENCESINFOVO = AttributesEnum.RecReferencesInfoVO.index();
    public static final int GENDERCODES1 = AttributesEnum.GenderCodes1.index();
    public static final int STATESVVO1 = AttributesEnum.StatesVVO1.index();
    public static final int CITIESVVO1 = AttributesEnum.CitiesVVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RecCandidateInfoVORowImpl() {
    }

    /**
     * Gets RecCandidateInfoEO entity object.
     * @return the RecCandidateInfoEO
     */
    public RecCandidateInfoEOImpl getRecCandidateInfoEO() {
        return (RecCandidateInfoEOImpl) getEntity(ENTITY_RECCANDIDATEINFOEO);
    }

    /**
     * Gets the attribute value for CANDIDATE_ID using the alias name CandidateId.
     * @return the CANDIDATE_ID
     */
    public BigDecimal getCandidateId() {
        return (BigDecimal) getAttributeInternal(CANDIDATEID);
    }

    /**
     * Sets <code>value</code> as attribute value for CANDIDATE_ID using the alias name CandidateId.
     * @param value value to set the CANDIDATE_ID
     */
    public void setCandidateId(BigDecimal value) {
        setAttributeInternal(CANDIDATEID, value);
    }

    /**
     * Gets the attribute value for FIRST_NAME using the alias name FirstName.
     * @return the FIRST_NAME
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FIRST_NAME using the alias name FirstName.
     * @param value value to set the FIRST_NAME
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**
     * Gets the attribute value for LAST_NAME using the alias name LastName.
     * @return the LAST_NAME
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_NAME using the alias name LastName.
     * @param value value to set the LAST_NAME
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**
     * Gets the attribute value for MIDDLE_NAME using the alias name MiddleName.
     * @return the MIDDLE_NAME
     */
    public String getMiddleName() {
        return (String) getAttributeInternal(MIDDLENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for MIDDLE_NAME using the alias name MiddleName.
     * @param value value to set the MIDDLE_NAME
     */
    public void setMiddleName(String value) {
        setAttributeInternal(MIDDLENAME, value);
    }

    /**
     * Gets the attribute value for DOB using the alias name Dob.
     * @return the DOB
     */
    public Timestamp getDob() {
        return (Timestamp) getAttributeInternal(DOB);
    }

    /**
     * Sets <code>value</code> as attribute value for DOB using the alias name Dob.
     * @param value value to set the DOB
     */
    public void setDob(Timestamp value) {
        setAttributeInternal(DOB, value);
    }

    /**
     * Gets the attribute value for GENDER using the alias name Gender.
     * @return the GENDER
     */
    public String getGender() {
        return (String) getAttributeInternal(GENDER);
    }

    /**
     * Sets <code>value</code> as attribute value for GENDER using the alias name Gender.
     * @param value value to set the GENDER
     */
    public void setGender(String value) {
        setAttributeInternal(GENDER, value);
    }

    /**
     * Gets the attribute value for EMAIL_ID using the alias name EmailId.
     * @return the EMAIL_ID
     */
    public String getEmailId() {
        return (String) getAttributeInternal(EMAILID);
    }

    /**
     * Sets <code>value</code> as attribute value for EMAIL_ID using the alias name EmailId.
     * @param value value to set the EMAIL_ID
     */
    public void setEmailId(String value) {
        setAttributeInternal(EMAILID, value);
    }

    /**
     * Gets the attribute value for MOBILE_NO using the alias name MobileNo.
     * @return the MOBILE_NO
     */
    public Long getMobileNo() {
        return (Long) getAttributeInternal(MOBILENO);
    }

    /**
     * Sets <code>value</code> as attribute value for MOBILE_NO using the alias name MobileNo.
     * @param value value to set the MOBILE_NO
     */
    public void setMobileNo(Long value) {
        setAttributeInternal(MOBILENO, value);
    }

    /**
     * Gets the attribute value for LANDLINE_NO using the alias name LandlineNo.
     * @return the LANDLINE_NO
     */
    public Long getLandlineNo() {
        return (Long) getAttributeInternal(LANDLINENO);
    }

    /**
     * Sets <code>value</code> as attribute value for LANDLINE_NO using the alias name LandlineNo.
     * @param value value to set the LANDLINE_NO
     */
    public void setLandlineNo(Long value) {
        setAttributeInternal(LANDLINENO, value);
    }

    /**
     * Gets the attribute value for ADDRESS using the alias name Address.
     * @return the ADDRESS
     */
    public String getAddress() {
        return (String) getAttributeInternal(ADDRESS);
    }

    /**
     * Sets <code>value</code> as attribute value for ADDRESS using the alias name Address.
     * @param value value to set the ADDRESS
     */
    public void setAddress(String value) {
        setAttributeInternal(ADDRESS, value);
    }

    /**
     * Gets the attribute value for PIN using the alias name Pin.
     * @return the PIN
     */
    public Integer getPin() {
        return (Integer) getAttributeInternal(PIN);
    }

    /**
     * Sets <code>value</code> as attribute value for PIN using the alias name Pin.
     * @param value value to set the PIN
     */
    public void setPin(Integer value) {
        setAttributeInternal(PIN, value);
    }

    /**
     * Gets the attribute value for CITY using the alias name City.
     * @return the CITY
     */
    public Integer getCity() {
        return (Integer) getAttributeInternal(CITY);
    }

    /**
     * Sets <code>value</code> as attribute value for CITY using the alias name City.
     * @param value value to set the CITY
     */
    public void setCity(Integer value) {
        setAttributeInternal(CITY, value);
    }

    /**
     * Gets the attribute value for STATE using the alias name State.
     * @return the STATE
     */
    public Integer getState() {
        return (Integer) getAttributeInternal(STATE);
    }

    /**
     * Sets <code>value</code> as attribute value for STATE using the alias name State.
     * @param value value to set the STATE
     */
    public void setState(Integer value) {
        setAttributeInternal(STATE, value);
    }

    /**
     * Gets the attribute value for RELOCATE using the alias name Relocate.
     * @return the RELOCATE
     */
    public String getRelocate() {
        return (String) getAttributeInternal(RELOCATE);
    }

    /**
     * Sets <code>value</code> as attribute value for RELOCATE using the alias name Relocate.
     * @param value value to set the RELOCATE
     */
    public void setRelocate(String value) {
        setAttributeInternal(RELOCATE, value);
    }

    /**
     * Gets the attribute value for TRAVEL using the alias name Travel.
     * @return the TRAVEL
     */
    public String getTravel() {
        return (String) getAttributeInternal(TRAVEL);
    }

    /**
     * Sets <code>value</code> as attribute value for TRAVEL using the alias name Travel.
     * @param value value to set the TRAVEL
     */
    public void setTravel(String value) {
        setAttributeInternal(TRAVEL, value);
    }

    /**
     * Gets the attribute value for REASONS_FOR_CHANGE using the alias name ReasonsForChange.
     * @return the REASONS_FOR_CHANGE
     */
    public String getReasonsForChange() {
        return (String) getAttributeInternal(REASONSFORCHANGE);
    }

    /**
     * Sets <code>value</code> as attribute value for REASONS_FOR_CHANGE using the alias name ReasonsForChange.
     * @param value value to set the REASONS_FOR_CHANGE
     */
    public void setReasonsForChange(String value) {
        setAttributeInternal(REASONSFORCHANGE, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link RecEduInfoVO.
     */
    public RowIterator getRecEduInfoVO() {
        return (RowIterator) getAttributeInternal(RECEDUINFOVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link RecExpInfoVO.
     */
    public RowIterator getRecExpInfoVO() {
        return (RowIterator) getAttributeInternal(RECEXPINFOVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link RecReferralInfoVO.
     */
    public RowIterator getRecReferralInfoVO() {
        return (RowIterator) getAttributeInternal(RECREFERRALINFOVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link RecReferencesInfoVO.
     */
    public RowIterator getRecReferencesInfoVO() {
        return (RowIterator) getAttributeInternal(RECREFERENCESINFOVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GenderCodes1.
     */
    public RowSet getGenderCodes1() {
        return (RowSet) getAttributeInternal(GENDERCODES1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StatesVVO1.
     */
    public RowSet getStatesVVO1() {
        return (RowSet) getAttributeInternal(STATESVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CitiesVVO1.
     */
    public RowSet getCitiesVVO1() {
        return (RowSet) getAttributeInternal(CITIESVVO1);
    }
}

