package model.vo;

import java.math.BigDecimal;

import model.eo.RecEmployeeInfoEOImpl;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 18 16:14:08 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RecEmployeeInfoVORowImpl extends ViewRowImpl {
    public static final int ENTITY_RECEMPLOYEEINFOEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        EmployeeId,
        EmpName,
        Designation,
        ManagerId;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int EMPLOYEEID = AttributesEnum.EmployeeId.index();
    public static final int EMPNAME = AttributesEnum.EmpName.index();
    public static final int DESIGNATION = AttributesEnum.Designation.index();
    public static final int MANAGERID = AttributesEnum.ManagerId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RecEmployeeInfoVORowImpl() {
    }

    /**
     * Gets RecEmployeeInfoEO entity object.
     * @return the RecEmployeeInfoEO
     */
    public RecEmployeeInfoEOImpl getRecEmployeeInfoEO() {
        return (RecEmployeeInfoEOImpl) getEntity(ENTITY_RECEMPLOYEEINFOEO);
    }

    /**
     * Gets the attribute value for EMPLOYEE_ID using the alias name EmployeeId.
     * @return the EMPLOYEE_ID
     */
    public BigDecimal getEmployeeId() {
        return (BigDecimal) getAttributeInternal(EMPLOYEEID);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYEE_ID using the alias name EmployeeId.
     * @param value value to set the EMPLOYEE_ID
     */
    public void setEmployeeId(BigDecimal value) {
        setAttributeInternal(EMPLOYEEID, value);
    }

    /**
     * Gets the attribute value for EMP_NAME using the alias name EmpName.
     * @return the EMP_NAME
     */
    public String getEmpName() {
        return (String) getAttributeInternal(EMPNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_NAME using the alias name EmpName.
     * @param value value to set the EMP_NAME
     */
    public void setEmpName(String value) {
        setAttributeInternal(EMPNAME, value);
    }

    /**
     * Gets the attribute value for DESIGNATION using the alias name Designation.
     * @return the DESIGNATION
     */
    public String getDesignation() {
        return (String) getAttributeInternal(DESIGNATION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESIGNATION using the alias name Designation.
     * @param value value to set the DESIGNATION
     */
    public void setDesignation(String value) {
        setAttributeInternal(DESIGNATION, value);
    }

    /**
     * Gets the attribute value for MANAGER_ID using the alias name ManagerId.
     * @return the MANAGER_ID
     */
    public BigDecimal getManagerId() {
        return (BigDecimal) getAttributeInternal(MANAGERID);
    }

    /**
     * Sets <code>value</code> as attribute value for MANAGER_ID using the alias name ManagerId.
     * @param value value to set the MANAGER_ID
     */
    public void setManagerId(BigDecimal value) {
        setAttributeInternal(MANAGERID, value);
    }
}

