package model.vo;

import java.math.BigDecimal;

import model.eo.RecEduInfoEOImpl;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 18 16:13:56 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RecEduInfoVORowImpl extends ViewRowImpl {

    public static final int ENTITY_RECEDUINFOEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        EduId,
        CandidatenId,
        QalificationId,
        InstituteName,
        YearOfCompletion,
        Percentage;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int EDUID = AttributesEnum.EduId.index();
    public static final int CANDIDATENID = AttributesEnum.CandidatenId.index();
    public static final int QALIFICATIONID = AttributesEnum.QalificationId.index();
    public static final int INSTITUTENAME = AttributesEnum.InstituteName.index();
    public static final int YEAROFCOMPLETION = AttributesEnum.YearOfCompletion.index();
    public static final int PERCENTAGE = AttributesEnum.Percentage.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RecEduInfoVORowImpl() {
    }

    /**
     * Gets RecEduInfoEO entity object.
     * @return the RecEduInfoEO
     */
    public RecEduInfoEOImpl getRecEduInfoEO() {
        return (RecEduInfoEOImpl) getEntity(ENTITY_RECEDUINFOEO);
    }

    /**
     * Gets the attribute value for EDU_ID using the alias name EduId.
     * @return the EDU_ID
     */
    public BigDecimal getEduId() {
        return (BigDecimal) getAttributeInternal(EDUID);
    }

    /**
     * Sets <code>value</code> as attribute value for EDU_ID using the alias name EduId.
     * @param value value to set the EDU_ID
     */
    public void setEduId(BigDecimal value) {
        setAttributeInternal(EDUID, value);
    }

    /**
     * Gets the attribute value for CANDIDATEN_ID using the alias name CandidatenId.
     * @return the CANDIDATEN_ID
     */
    public BigDecimal getCandidatenId() {
        return (BigDecimal) getAttributeInternal(CANDIDATENID);
    }

    /**
     * Sets <code>value</code> as attribute value for CANDIDATEN_ID using the alias name CandidatenId.
     * @param value value to set the CANDIDATEN_ID
     */
    public void setCandidatenId(BigDecimal value) {
        setAttributeInternal(CANDIDATENID, value);
    }

    /**
     * Gets the attribute value for QALIFICATION_ID using the alias name QalificationId.
     * @return the QALIFICATION_ID
     */
    public BigDecimal getQalificationId() {
        return (BigDecimal) getAttributeInternal(QALIFICATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for QALIFICATION_ID using the alias name QalificationId.
     * @param value value to set the QALIFICATION_ID
     */
    public void setQalificationId(BigDecimal value) {
        setAttributeInternal(QALIFICATIONID, value);
    }

    /**
     * Gets the attribute value for INSTITUTE_NAME using the alias name InstituteName.
     * @return the INSTITUTE_NAME
     */
    public String getInstituteName() {
        return (String) getAttributeInternal(INSTITUTENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for INSTITUTE_NAME using the alias name InstituteName.
     * @param value value to set the INSTITUTE_NAME
     */
    public void setInstituteName(String value) {
        setAttributeInternal(INSTITUTENAME, value);
    }

    /**
     * Gets the attribute value for YEAR_OF_COMPLETION using the alias name YearOfCompletion.
     * @return the YEAR_OF_COMPLETION
     */
    public Integer getYearOfCompletion() {
        return (Integer) getAttributeInternal(YEAROFCOMPLETION);
    }

    /**
     * Sets <code>value</code> as attribute value for YEAR_OF_COMPLETION using the alias name YearOfCompletion.
     * @param value value to set the YEAR_OF_COMPLETION
     */
    public void setYearOfCompletion(Integer value) {
        setAttributeInternal(YEAROFCOMPLETION, value);
    }

    /**
     * Gets the attribute value for PERCENTAGE using the alias name Percentage.
     * @return the PERCENTAGE
     */
    public String getPercentage() {
        return (String) getAttributeInternal(PERCENTAGE);
    }

    /**
     * Sets <code>value</code> as attribute value for PERCENTAGE using the alias name Percentage.
     * @param value value to set the PERCENTAGE
     */
    public void setPercentage(String value) {
        setAttributeInternal(PERCENTAGE, value);
    }
}

