package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import model.eo.RecInterviewInfoEOImpl;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 18 16:14:32 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RecInterviewInfoVORowImpl extends ViewRowImpl {
    public static final int ENTITY_RECINTERVIEWINFOEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        InterviewId,
        CandidateId,
        InterviewerId,
        Feedback,
        Description,
        Status;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int INTERVIEWID = AttributesEnum.InterviewId.index();
    public static final int CANDIDATEID = AttributesEnum.CandidateId.index();
    public static final int INTERVIEWERID = AttributesEnum.InterviewerId.index();
    public static final int FEEDBACK = AttributesEnum.Feedback.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int STATUS = AttributesEnum.Status.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RecInterviewInfoVORowImpl() {
    }

    /**
     * Gets RecInterviewInfoEO entity object.
     * @return the RecInterviewInfoEO
     */
    public RecInterviewInfoEOImpl getRecInterviewInfoEO() {
        return (RecInterviewInfoEOImpl) getEntity(ENTITY_RECINTERVIEWINFOEO);
    }

    /**
     * Gets the attribute value for INTERVIEW_ID using the alias name InterviewId.
     * @return the INTERVIEW_ID
     */
    public BigDecimal getInterviewId() {
        return (BigDecimal) getAttributeInternal(INTERVIEWID);
    }

    /**
     * Sets <code>value</code> as attribute value for INTERVIEW_ID using the alias name InterviewId.
     * @param value value to set the INTERVIEW_ID
     */
    public void setInterviewId(BigDecimal value) {
        setAttributeInternal(INTERVIEWID, value);
    }

    /**
     * Gets the attribute value for CANDIDATE_ID using the alias name CandidateId.
     * @return the CANDIDATE_ID
     */
    public BigDecimal getCandidateId() {
        return (BigDecimal) getAttributeInternal(CANDIDATEID);
    }

    /**
     * Sets <code>value</code> as attribute value for CANDIDATE_ID using the alias name CandidateId.
     * @param value value to set the CANDIDATE_ID
     */
    public void setCandidateId(BigDecimal value) {
        setAttributeInternal(CANDIDATEID, value);
    }

    /**
     * Gets the attribute value for INTERVIEWER_ID using the alias name InterviewerId.
     * @return the INTERVIEWER_ID
     */
    public BigDecimal getInterviewerId() {
        return (BigDecimal) getAttributeInternal(INTERVIEWERID);
    }

    /**
     * Sets <code>value</code> as attribute value for INTERVIEWER_ID using the alias name InterviewerId.
     * @param value value to set the INTERVIEWER_ID
     */
    public void setInterviewerId(BigDecimal value) {
        setAttributeInternal(INTERVIEWERID, value);
    }

    /**
     * Gets the attribute value for FEEDBACK using the alias name Feedback.
     * @return the FEEDBACK
     */
    public Timestamp getFeedback() {
        return (Timestamp) getAttributeInternal(FEEDBACK);
    }

    /**
     * Sets <code>value</code> as attribute value for FEEDBACK using the alias name Feedback.
     * @param value value to set the FEEDBACK
     */
    public void setFeedback(Timestamp value) {
        setAttributeInternal(FEEDBACK, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }
}

