package model.vo;

import java.math.BigDecimal;

import model.eo.RecReferencesInfoEOImpl;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 18 16:14:44 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RecReferencesInfoVORowImpl extends ViewRowImpl {

    public static final int ENTITY_RECREFERENCESINFOEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        RefId,
        CandidateId,
        RefName,
        Designation,
        EmailId,
        TelephoneNo,
        Organization,
        Address,
        ProfRelation,
        Association;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int REFID = AttributesEnum.RefId.index();
    public static final int CANDIDATEID = AttributesEnum.CandidateId.index();
    public static final int REFNAME = AttributesEnum.RefName.index();
    public static final int DESIGNATION = AttributesEnum.Designation.index();
    public static final int EMAILID = AttributesEnum.EmailId.index();
    public static final int TELEPHONENO = AttributesEnum.TelephoneNo.index();
    public static final int ORGANIZATION = AttributesEnum.Organization.index();
    public static final int ADDRESS = AttributesEnum.Address.index();
    public static final int PROFRELATION = AttributesEnum.ProfRelation.index();
    public static final int ASSOCIATION = AttributesEnum.Association.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RecReferencesInfoVORowImpl() {
    }

    /**
     * Gets RecReferencesInfoEO entity object.
     * @return the RecReferencesInfoEO
     */
    public RecReferencesInfoEOImpl getRecReferencesInfoEO() {
        return (RecReferencesInfoEOImpl) getEntity(ENTITY_RECREFERENCESINFOEO);
    }

    /**
     * Gets the attribute value for REF_ID using the alias name RefId.
     * @return the REF_ID
     */
    public BigDecimal getRefId() {
        return (BigDecimal) getAttributeInternal(REFID);
    }

    /**
     * Sets <code>value</code> as attribute value for REF_ID using the alias name RefId.
     * @param value value to set the REF_ID
     */
    public void setRefId(BigDecimal value) {
        setAttributeInternal(REFID, value);
    }

    /**
     * Gets the attribute value for CANDIDATE_ID using the alias name CandidateId.
     * @return the CANDIDATE_ID
     */
    public BigDecimal getCandidateId() {
        return (BigDecimal) getAttributeInternal(CANDIDATEID);
    }

    /**
     * Sets <code>value</code> as attribute value for CANDIDATE_ID using the alias name CandidateId.
     * @param value value to set the CANDIDATE_ID
     */
    public void setCandidateId(BigDecimal value) {
        setAttributeInternal(CANDIDATEID, value);
    }

    /**
     * Gets the attribute value for REF_NAME using the alias name RefName.
     * @return the REF_NAME
     */
    public String getRefName() {
        return (String) getAttributeInternal(REFNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for REF_NAME using the alias name RefName.
     * @param value value to set the REF_NAME
     */
    public void setRefName(String value) {
        setAttributeInternal(REFNAME, value);
    }

    /**
     * Gets the attribute value for DESIGNATION using the alias name Designation.
     * @return the DESIGNATION
     */
    public String getDesignation() {
        return (String) getAttributeInternal(DESIGNATION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESIGNATION using the alias name Designation.
     * @param value value to set the DESIGNATION
     */
    public void setDesignation(String value) {
        setAttributeInternal(DESIGNATION, value);
    }

    /**
     * Gets the attribute value for EMAIL_ID using the alias name EmailId.
     * @return the EMAIL_ID
     */
    public String getEmailId() {
        return (String) getAttributeInternal(EMAILID);
    }

    /**
     * Sets <code>value</code> as attribute value for EMAIL_ID using the alias name EmailId.
     * @param value value to set the EMAIL_ID
     */
    public void setEmailId(String value) {
        setAttributeInternal(EMAILID, value);
    }

    /**
     * Gets the attribute value for TELEPHONE_NO using the alias name TelephoneNo.
     * @return the TELEPHONE_NO
     */
    public Long getTelephoneNo() {
        return (Long) getAttributeInternal(TELEPHONENO);
    }

    /**
     * Sets <code>value</code> as attribute value for TELEPHONE_NO using the alias name TelephoneNo.
     * @param value value to set the TELEPHONE_NO
     */
    public void setTelephoneNo(Long value) {
        setAttributeInternal(TELEPHONENO, value);
    }

    /**
     * Gets the attribute value for ORGANIZATION using the alias name Organization.
     * @return the ORGANIZATION
     */
    public String getOrganization() {
        return (String) getAttributeInternal(ORGANIZATION);
    }

    /**
     * Sets <code>value</code> as attribute value for ORGANIZATION using the alias name Organization.
     * @param value value to set the ORGANIZATION
     */
    public void setOrganization(String value) {
        setAttributeInternal(ORGANIZATION, value);
    }

    /**
     * Gets the attribute value for ADDRESS using the alias name Address.
     * @return the ADDRESS
     */
    public String getAddress() {
        return (String) getAttributeInternal(ADDRESS);
    }

    /**
     * Sets <code>value</code> as attribute value for ADDRESS using the alias name Address.
     * @param value value to set the ADDRESS
     */
    public void setAddress(String value) {
        setAttributeInternal(ADDRESS, value);
    }

    /**
     * Gets the attribute value for PROF_RELATION using the alias name ProfRelation.
     * @return the PROF_RELATION
     */
    public String getProfRelation() {
        return (String) getAttributeInternal(PROFRELATION);
    }

    /**
     * Sets <code>value</code> as attribute value for PROF_RELATION using the alias name ProfRelation.
     * @param value value to set the PROF_RELATION
     */
    public void setProfRelation(String value) {
        setAttributeInternal(PROFRELATION, value);
    }

    /**
     * Gets the attribute value for ASSOCIATION using the alias name Association.
     * @return the ASSOCIATION
     */
    public String getAssociation() {
        return (String) getAttributeInternal(ASSOCIATION);
    }

    /**
     * Sets <code>value</code> as attribute value for ASSOCIATION using the alias name Association.
     * @param value value to set the ASSOCIATION
     */
    public void setAssociation(String value) {
        setAttributeInternal(ASSOCIATION, value);
    }
}

