package model.eo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 14 11:35:55 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TimeSheetWeekHoursEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        TimeSheetId,
        DayId,
        Day,
        HoursPerDay,
        Notes,
        TimeSheetWeekEO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int TIMESHEETID = AttributesEnum.TimeSheetId.index();
    public static final int DAYID = AttributesEnum.DayId.index();
    public static final int DAY = AttributesEnum.Day.index();
    public static final int HOURSPERDAY = AttributesEnum.HoursPerDay.index();
    public static final int NOTES = AttributesEnum.Notes.index();
    public static final int TIMESHEETWEEKEO = AttributesEnum.TimeSheetWeekEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TimeSheetWeekHoursEOImpl() {
    }

    /**
     * Gets the attribute value for TimeSheetId, using the alias name TimeSheetId.
     * @return the value of TimeSheetId
     */
    public BigDecimal getTimeSheetId() {
        return (BigDecimal) getAttributeInternal(TIMESHEETID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TimeSheetId.
     * @param value value to set the TimeSheetId
     */
    public void setTimeSheetId(BigDecimal value) {
        setAttributeInternal(TIMESHEETID, value);
    }

    /**
     * Gets the attribute value for DayId, using the alias name DayId.
     * @return the value of DayId
     */
    public DBSequence getDayId() {
        return (DBSequence) getAttributeInternal(DAYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DayId.
     * @param value value to set the DayId
     */
    public void setDayId(DBSequence value) {
        setAttributeInternal(DAYID, value);
    }

    /**
     * Gets the attribute value for Day, using the alias name Day.
     * @return the value of Day
     */
    public Timestamp getDay() {
        return (Timestamp) getAttributeInternal(DAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day.
     * @param value value to set the Day
     */
    public void setDay(Timestamp value) {
        setAttributeInternal(DAY, value);
    }

    /**
     * Gets the attribute value for HoursPerDay, using the alias name HoursPerDay.
     * @return the value of HoursPerDay
     */
    public BigDecimal getHoursPerDay() {
        return (BigDecimal) getAttributeInternal(HOURSPERDAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for HoursPerDay.
     * @param value value to set the HoursPerDay
     */
    public void setHoursPerDay(BigDecimal value) {
        setAttributeInternal(HOURSPERDAY, value);
    }

    /**
     * Gets the attribute value for Notes, using the alias name Notes.
     * @return the value of Notes
     */
    public String getNotes() {
        return (String) getAttributeInternal(NOTES);
    }

    /**
     * Sets <code>value</code> as the attribute value for Notes.
     * @param value value to set the Notes
     */
    public void setNotes(String value) {
        setAttributeInternal(NOTES, value);
    }

    /**
     * @return the associated entity TimeSheetWeekEOImpl.
     */
    public TimeSheetWeekEOImpl getTimeSheetWeekEO() {
        return (TimeSheetWeekEOImpl) getAttributeInternal(TIMESHEETWEEKEO);
    }

    /**
     * Sets <code>value</code> as the associated entity TimeSheetWeekEOImpl.
     */
    public void setTimeSheetWeekEO(TimeSheetWeekEOImpl value) {
        setAttributeInternal(TIMESHEETWEEKEO, value);
    }

    /**
     * @param dayId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(DBSequence dayId) {
        return new Key(new Object[] { dayId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.eo.TimeSheetWeekHoursEO");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        this.setDayId(new DBSequence(new SequenceImpl("TIMESHEET_WEEK_ID_SEQ",getDBTransaction()).getSequenceNumber().longValue()));
    }
}

