package model.eo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.BFileDomain;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 14 19:03:12 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TimeSheetDaysEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        WeekId,
        Day1,
        Day2,
        Day3,
        Day4,
        Day5,
        Day6,
        Day7,
        TimeSheetId,
        TaskId,
        TimeSheetWeekEO1,
        TimeSheetWeekEO;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int WEEKID = AttributesEnum.WeekId.index();
    public static final int DAY1 = AttributesEnum.Day1.index();
    public static final int DAY2 = AttributesEnum.Day2.index();
    public static final int DAY3 = AttributesEnum.Day3.index();
    public static final int DAY4 = AttributesEnum.Day4.index();
    public static final int DAY5 = AttributesEnum.Day5.index();
    public static final int DAY6 = AttributesEnum.Day6.index();
    public static final int DAY7 = AttributesEnum.Day7.index();
    public static final int TIMESHEETID = AttributesEnum.TimeSheetId.index();
    public static final int TASKID = AttributesEnum.TaskId.index();
    public static final int TIMESHEETWEEKEO1 = AttributesEnum.TimeSheetWeekEO1.index();
    public static final int TIMESHEETWEEKEO = AttributesEnum.TimeSheetWeekEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public TimeSheetDaysEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.eo.TimeSheetDaysEO");
    }


    /**
     * Gets the attribute value for WeekId, using the alias name WeekId.
     * @return the value of WeekId
     */
    public BigDecimal getWeekId() {
        return (BigDecimal) getAttributeInternal(WEEKID);
    }

    /**
     * Sets <code>value</code> as the attribute value for WeekId.
     * @param value value to set the WeekId
     */
    public void setWeekId(BigDecimal value) {
        setAttributeInternal(WEEKID, value);
    }

    /**
     * Gets the attribute value for Day1, using the alias name Day1.
     * @return the value of Day1
     */
    public Integer getDay1() {
        return (Integer) getAttributeInternal(DAY1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day1.
     * @param value value to set the Day1
     */
    public void setDay1(Integer value) {
        setAttributeInternal(DAY1, value);
    }

    /**
     * Gets the attribute value for Day2, using the alias name Day2.
     * @return the value of Day2
     */
    public Integer getDay2() {
        return (Integer) getAttributeInternal(DAY2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day2.
     * @param value value to set the Day2
     */
    public void setDay2(Integer value) {
        setAttributeInternal(DAY2, value);
    }

    /**
     * Gets the attribute value for Day3, using the alias name Day3.
     * @return the value of Day3
     */
    public Integer getDay3() {
        return (Integer) getAttributeInternal(DAY3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day3.
     * @param value value to set the Day3
     */
    public void setDay3(Integer value) {
        setAttributeInternal(DAY3, value);
    }

    /**
     * Gets the attribute value for Day4, using the alias name Day4.
     * @return the value of Day4
     */
    public Integer getDay4() {
        return (Integer) getAttributeInternal(DAY4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day4.
     * @param value value to set the Day4
     */
    public void setDay4(Integer value) {
        setAttributeInternal(DAY4, value);
    }

    /**
     * Gets the attribute value for Day5, using the alias name Day5.
     * @return the value of Day5
     */
    public Integer getDay5() {
        return (Integer) getAttributeInternal(DAY5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day5.
     * @param value value to set the Day5
     */
    public void setDay5(Integer value) {
        setAttributeInternal(DAY5, value);
    }

    /**
     * Gets the attribute value for Day6, using the alias name Day6.
     * @return the value of Day6
     */
    public Integer getDay6() {
        return (Integer) getAttributeInternal(DAY6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day6.
     * @param value value to set the Day6
     */
    public void setDay6(Integer value) {
        setAttributeInternal(DAY6, value);
    }

    /**
     * Gets the attribute value for Day7, using the alias name Day7.
     * @return the value of Day7
     */
    public Integer getDay7() {
        return (Integer) getAttributeInternal(DAY7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Day7.
     * @param value value to set the Day7
     */
    public void setDay7(Integer value) {
        setAttributeInternal(DAY7, value);
    }

    /**
     * Gets the attribute value for TimeSheetId, using the alias name TimeSheetId.
     * @return the value of TimeSheetId
     */
    public BigDecimal getTimeSheetId() {
        return (BigDecimal) getAttributeInternal(TIMESHEETID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TimeSheetId.
     * @param value value to set the TimeSheetId
     */
    public void setTimeSheetId(BigDecimal value) {
        setAttributeInternal(TIMESHEETID, value);
    }


    /**
     * Gets the attribute value for TaskId, using the alias name TaskId.
     * @return the value of TaskId
     */
    public BigDecimal getTaskId() {
        return (BigDecimal) getAttributeInternal(TASKID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TaskId.
     * @param value value to set the TaskId
     */
    public void setTaskId(BigDecimal value) {
        setAttributeInternal(TASKID, value);
    }

    /**
     * @return the associated entity TimeSheetWeekEOImpl.
     */
    public TimeSheetWeekEOImpl getTimeSheetWeekEO1() {
        return (TimeSheetWeekEOImpl) getAttributeInternal(TIMESHEETWEEKEO1);
    }

    /**
     * Sets <code>value</code> as the associated entity TimeSheetWeekEOImpl.
     */
    public void setTimeSheetWeekEO1(TimeSheetWeekEOImpl value) {
        setAttributeInternal(TIMESHEETWEEKEO1, value);
    }


    /**
     * @return the associated entity TimeSheetWeekEOImpl.
     */
    public TimeSheetWeekEOImpl getTimeSheetWeekEO() {
        return (TimeSheetWeekEOImpl) getAttributeInternal(TIMESHEETWEEKEO);
    }

    /**
     * Sets <code>value</code> as the associated entity TimeSheetWeekEOImpl.
     */
    public void setTimeSheetWeekEO(TimeSheetWeekEOImpl value) {
        setAttributeInternal(TIMESHEETWEEKEO, value);
    }


    /**
     * @param weekId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal weekId) {
        return new Key(new Object[] { weekId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        this.setWeekId(new SequenceImpl("TIMESHEET_WEEKDAY_SEQ",getDBTransaction()).getSequenceNumber().getBigDecimalValue());
    }
}

